'use client'

import { motion } from 'framer-motion'
import { pageVariants, sectionReveal, viewportConfig } from '@/lib/animations'
import { SectionLabel } from '@/components/ui/SectionLabel'

const sections = [
  {
    title: 'Acceptance of Terms',
    body: 'By downloading, installing, or using Divine Connect, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, do not use our services. These terms constitute a legally binding agreement between you and DevBhumi Technologies Pvt. Ltd., a company incorporated under the laws of India.',
  },
  {
    title: 'Description of Service',
    body: 'Divine Connect is an AI-powered spiritual companion app that provides access to Hindu scriptures, deity conversations, Panchang (Hindu calendar), mantra guidance, and related spiritual content. The service is provided "as is" and is intended for informational, educational, and devotional purposes only.\n\nDivine Connect is NOT a substitute for qualified religious counsel, medical advice, psychological therapy, or legal guidance. Content generated by our AI is based on scriptural sources but may not reflect every regional tradition or the views of all Hindu denominations.',
  },
  {
    title: 'Eligibility',
    body: 'You must be at least 13 years of age to use Divine Connect. By using the service, you represent that you are 13 or older. Users between 13 and 18 should use the service with parental guidance. We reserve the right to terminate accounts of users found to be under 13.',
  },
  {
    title: 'User Accounts',
    body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately at support@devbhumi.com if you suspect unauthorised access. We are not liable for losses resulting from unauthorised use of your account.',
  },
  {
    title: 'Acceptable Use',
    body: 'You agree not to:\n\n• Use Divine Connect to generate, distribute, or promote content that is hateful, defamatory, or disrespectful of religious traditions\n• Attempt to reverse-engineer, scrape, or extract our AI models, training data, or scripture databases\n• Use automated bots or scripts to access the service\n• Resell or sublicense access to Divine Connect\n• Use the service for any purpose that violates Indian law or applicable international law\n• Attempt to circumvent subscription paywalls or access premium features without payment',
  },
  {
    title: 'Intellectual Property',
    body: 'All content, features, and functionality of Divine Connect — including but not limited to text, graphics, logos, AI models, and software — are owned by or licensed to DevBhumi Technologies Pvt. Ltd. and are protected by Indian and international intellectual property law.\n\nAncient scriptures (Vedas, Upanishads, Puranas, etc.) are in the public domain. Our translations, commentary, AI synthesis, and curation of these texts are proprietary.\n\nYou retain ownership of any content you submit to Divine Connect (e.g., journal entries). By submitting content, you grant us a non-exclusive licence to use it to improve our services.',
  },
  {
    title: 'Subscriptions & Payments',
    body: 'Certain features require a paid subscription. By subscribing, you authorise us to charge your payment method on a recurring basis. Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date.\n\nRefunds are governed by our Refund Policy. We generally offer a 7-day refund for annual subscriptions if requested within 7 days of purchase and no premium features have been used. Monthly subscriptions are non-refundable.',
  },
  {
    title: 'Disclaimers',
    body: 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, DIVINE CONNECT IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.\n\nAI-generated spiritual guidance is probabilistic and based on training data. It may be incomplete or imperfect. Always consult a qualified pandit or religious authority for critical spiritual, ritual, or personal decisions.',
  },
  {
    title: 'Limitation of Liability',
    body: 'To the extent permitted by Indian law, DevBhumi Technologies Pvt. Ltd.\'s total liability to you for any claim arising out of these Terms or your use of the service will not exceed the amount you paid to us in the three months preceding the claim, or ₹500, whichever is greater.',
  },
  {
    title: 'Governing Law & Disputes',
    body: 'These Terms are governed by the laws of India. Any disputes arising under these Terms will be subject to the exclusive jurisdiction of courts in Bengaluru, Karnataka. Before initiating formal proceedings, you agree to first contact us at legal@devbhumi.com to attempt resolution in good faith.',
  },
  {
    title: 'Changes to Terms',
    body: 'We may modify these Terms at any time. We will notify you of material changes via in-app notification or email at least 14 days before they take effect. Your continued use of Divine Connect after the effective date constitutes acceptance of the revised Terms.',
  },
]

export default function TermsOfServicePage() {
  return (
    <motion.div variants={pageVariants} initial="initial" animate="animate" exit="exit" className="pt-16">
      <section className="py-20 md:py-28">
        <div className="max-w-3xl mx-auto px-6">
          <motion.div variants={sectionReveal} initial="hidden" whileInView="visible" viewport={viewportConfig} className="mb-12">
            <SectionLabel number="Legal" label="Terms of Service" />
            <h1
              className="font-[family-name:var(--font-cormorant)] text-ink-50 font-light leading-tight mb-4"
              style={{ fontSize: 'clamp(36px, 5vw, 60px)' }}
            >
              Terms of Service
            </h1>
            <p className="text-sm text-ink-600">Last updated: April 22, 2026 &middot; Effective: April 22, 2026</p>
          </motion.div>

          <div className="space-y-10">
            {sections.map((s, i) => (
              <motion.div
                key={s.title}
                variants={sectionReveal}
                initial="hidden"
                whileInView="visible"
                viewport={viewportConfig}
                className="border-t border-border-subtle pt-8"
              >
                <h2 className="text-ink-100 font-medium text-lg mb-4">
                  {i + 1}. {s.title}
                </h2>
                <div className="text-ink-400 text-sm leading-[1.8]">
                  {s.body.split('\n').map((line, j) => {
                    if (line.startsWith('• ')) return <p key={j} className="mb-2 pl-4">{line}</p>
                    if (line.trim() === '') return <br key={j} />
                    return <p key={j} className="mb-3">{line}</p>
                  })}
                </div>
              </motion.div>
            ))}
          </div>

          <motion.div
            variants={sectionReveal}
            initial="hidden"
            whileInView="visible"
            viewport={viewportConfig}
            className="mt-16 border-t border-border-subtle pt-8 text-sm text-ink-500"
          >
            <p className="mb-2">DevBhumi Technologies Pvt. Ltd.</p>
            <p className="mb-2">Bengaluru, Karnataka, India</p>
            <p>Contact: <a href="mailto:legal@devbhumi.com" className="text-saffron-400 hover:underline">legal@devbhumi.com</a></p>
          </motion.div>
        </div>
      </section>
    </motion.div>
  )
}
